services:
  client:
    build:
      context: .
      args:
        - BUILD_CONFIGURATION=Debug
    ports:
      - "5000:5000"  # Expose the port used by Kestrel
      - "5001:5001"  # If using HTTPS
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    depends_on:
      db:
        condition: service_healthy

  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: apotheosis
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d apotheosis"]
      interval: 10s
      timeout: 5s
      retries: 5
  
volumes:
  db-data:    